
#' A function to save the zhobo danmu into data.frame.
#' @param sec in seconds
#' @param rmid room id
#' @param visitid visit ID
#' @return Reture Data.frame
#' @keywords basic
#' @author Xia Yiwei
#' @export
#' @examples
#'


savehtml<-function(sec,rmid,visitid) {
  library("httr")
  library("jsonlite")
  ################################################
  page<-list()
  i=1
  time=Sys.time()
  while (i <=sec ) {
    URL="https://api.live.bilibili.com/ajax/msg"
    result<-POST(URL, body = list(
      "roomid"   = rmid,
      "visit_id" =visitid,
      'csrf_token'=''
      )
    )
    outcome<-jsonlite::fromJSON(txt=content(result, as="text"),simplifyDataFrame=TRUE)
    result<-as.data.frame(outcome$data$room)
    #pagename<-paste0("pg",format(Sys.time(), "%H_%M_%S"))
    print(Sys.time()) #record
    page[[i]]<-result
    if ((Sys.time()-time)==1) i=i+1
  }
  ##################################################################
  
  temp=page[[1]]
  temp$medal<-as.character(temp$medal)
  temp$title<-as.character(temp$title)
  temp$user_level<-as.character(temp$user_level)
  temp$activity_info<-as.character(temp$activity_info)

  for (i in 2:length(page)) {
    temp2<-page[[i]]
    temp2$medal<-as.character(temp2$medal)
    temp2$title<-as.character(temp2$title)
    temp2$user_level<-as.character(temp2$user_level)
    temp2$activity_info<-as.character(temp2$activity_info)
    #rownames(temp2)<-1*10-10+(1:nrow(temp2))
    temp<-rbind(temp,temp2)
  }

  temp<-temp[!duplicated(temp), ]
  return(temp)
} 


#' A function to convert txt file generated by Danmuji to data.frame
#' @param filename file names
#' @return Reture Data.frame
#' @keywords basic
#' @author Xia Yiwei
#' @export
#' @examples
#'

danmuji<-function(filename) {
library("stringr")
type<-vector()
time<-vector()
id<-vector()
item<-vector()
quant<-vector()
text<-vector()
idye<-vector()
idguan<-vector()

data<-readLines(filename,encoding = "UTF-8")
for (i in 1:length(data)) {
  if (!str_detect(data[i],"收到")) next
  if ( str_detect(data[i],"道具")) {
    type[i]="daoju"
    time[i]=str_extract(data[i],"[0-9][0-9]:[0-9][0-9]:[0-9][0-9]")
    id[i]=str_trim(str_sub(data[i],
                                str_locate(data[i],"道具:")[2]+1,
                                str_locate(data[i],"赠送")[1]-1))	
    id[i]=str_replace_all(id[i],"[爷]|[管]","")	
    
    item[i]=str_trim(str_sub(data[i],
                                  str_locate(data[i],"赠送的:")[2]+1,
                                  str_locate(data[i],"x")[1]-1))
    quant[i]=str_trim(str_sub(data[i],
                                  str_locate(data[i],"x")[2]+1))
    idye[i]=str_detect(data[i],"[爷]")
    idguan[i]=str_detect(data[i],"[管]")
    text[i]=NA
  } else if (str_detect(data[i],"彈幕")) {
    type[i]="danmu"
    time[i]=str_extract(data[i],"[0-9][0-9]:[0-9][0-9]:[0-9][0-9]")
    id[i]=str_trim(str_sub(data[i],
                                str_locate(data[i],"彈幕:")[2]+1,
                                str_locate(data[i],"說")[1]-1))	
    id[i]=str_replace_all(id[i],"[爷]|[管]","")	
    item[i]=NA
    quant[i]=NA
    text[i]=str_trim(str_sub(data[i],str_locate(data[i],"說:")[2]+1))
    idye[i]=str_detect(data[i],"[爷]")
    idguan[i]=str_detect(data[i],"[管]")
  }
}

datafin<-as.data.frame(cbind(type,time,id,item,quant,text,idye,idguan)) 
datafin<-datafin[!is.na(datafin$type),]

return(datafin)
}


#' A function to cut video into images using ffmpeg
#' @param filename file names
#' @param fps images per seconds
#' @return Reture Data.frame
#' @keywords basic
#' @author Xia Yiwei
#' @export
#' @examples
#'
cutvideo<-function(filename,fps,fmt="jpeg") {
  unlink('photos', recursive=TRUE)
  dir.create(file.path("photos"), showWarnings = FALSE)
  cmd=paste0("ffmpeg -i \"",filename,"\" -r ",fps," photos/output_%05d.",fmt)
  system(cmd)
}

#' A function to cut video into images using ffmpeg
#' @param filename file names
#' @param newformat for mate the 
#' @return Reture Data.frame
#' @keywords basic
#' @author Xia Yiwei
#' @export
#' @examples
#'
transformate<-function(filename,newformat) {
  unlink('convout', recursive=TRUE)
  dir.create(file.path("convout"), showWarnings = FALSE)
  cmd=paste0("ffmpeg -i ",filename, " convout/output.",newformat)
  system(cmd)
}

#' Post image to face++ and return emotion
#' @param img.path the path of image
#' @param apikey api key
#' @param seqkey secrit key
#' @return data.frame
#' @keywords basic
#' @author Xia Yiwei
#' @export
#' @examples
#'

faceplusplus_e<-function(img.path,apikey="i6aAp-TZNec1-HjPlzJS1oAaEcdRUHxi",seqkey= "dwobv2uNCA0MvUNTNwIiEmqQEn8jGGLR") {
  library("httr")
  library("imager")
  library("stringr")
  
  a<-POST("https://api-us.faceplusplus.com/facepp/v3/detect",
          body=list(
            "api_key" =apikey ,
            "api_secret" =seqkey,
            "image_file" =  upload_file(img.path),
            "return_landmark" = "1",
            "return_attributes" = "gender,age,smiling,headpose,facequality,blur,eyestatus,emotion,ethnicity,beauty,mouthstatus,eyegaze"
          ),
          verbose()
  )
  output<-httr::content(a)
  df=unlist(output$faces, use.names=TRUE)
  if (length(df)!=0) {
    fin=df[str_detect(names(df),"emotion")]
    names(fin)<-str_replace(names(fin),"attributes.emotion.","")
  } else {
    fin=data.frame("sadness"=NA,"neutral"=NA,"disgust"=NA,"anger"=NA,
               "surprise"=NA,"fear"=NA,"happiness"=NA)
  }
  return(fin)
}


###############################################################
#test Zone
#####################################################

# setwd("C:/Users/xiayi_000/OneDrive/主播视频分析/test")
# page<-savehtml(sec=600,rmid=5096,visitid="anwxaam4gnb4")


setwd("C:/Users/xiayi_000/Documents/弹幕姬")
setwd("C:/Users/xiayi_000/OneDrive/主播视频分析/测试视频")
cutvideo(filename="test.flv",fps=12)
transformate("test.flv",newformat = "mp4")

###############

temp<-data.frame("time"=NA,"sadness"=NA,"neutral"=NA,"disgust"=NA,"anger"=NA,
                 "surprise"=NA,"fear"=NA,"happiness"=NA)
fps=12
path<-"C:/Users/xiayi_000/OneDrive/主播视频分析/测试视频/photos"
setwd(path)

for (i in dir(path)) {
  a<-faceplusplus_e(i)
  nam=paste0(as.numeric(str_extract(i,"[0-9]+"))%/%fps,"_",
             as.numeric(str_extract(i,"[0-9]+"))%%fps) 
  tobeupdate<-c(time=nam,a)
  temp<-rbind(temp,tobeupdate)
}
